### ISSUE TITLE
Delay in playing large playlists

### ISSUE THREAD

**Issue by miketunes** [maykar/plex_assistant#114]
My All Music playlist has 28k tracks.  There is a 60 second delay before the music starts when I say this: Tell plex to shuffle all music playlist.  Is there anyway to speed this up or should it take that long?  My plex server and media are hosted on a 7th generation i5 processor Windows pc.  HA is on Raspberry Pi4.

trigger method: IFTTT
install method: HACS
logs: https://justpaste.it/93kuq

**Comment by maykar** [comment]
Depending on the specs of the Pi4 some operations can take some time, especially the lower models. In reference to your earlier related issue and it might help with this one as well, there is no "all" command. Try saying `"Tell plex to play random music"`.

**Comment by maykar** [comment]
Also, please do not post your entire debug log. It is well over 10,000 lines of information that have nothing to do with this project, just turn on debug for Plex Assistant only and post only the relevant information.

**Comment by maykar** [comment]
While looking through the logs I also noticed that Plex Assistant sends the command to play the playlist to home assistant within a few seconds, from then on the delay is between HA and your device.

Try playing a playlist using the play_media service in developer tools and see if you see the same behavior. If that's the case, Plex Assistant isn't the culprit here.

**Comment by miketunes** [comment]
Thanks for the response.  The tell plex to play random music still has a 1 minute delay.  Would you recommend moving plex to the raspberry pi where HA is hosted instead of a Windows pc?  I tried using the play_media service but it didn't seem to work, I was just guessing at the syntax though: https://imgur.com/a/2RAeaBl

I'll try to post cleaner logs, I had edited the configuration.yaml file with this:  custom_components.plex_assistant: debug
Is there a place that only shows the plex assistant logs?

**Comment by maykar** [comment]
Moving Plex to a raspberry pi would undoubtedly make things worse. To use the play_media service with plex media you would do so as explained here: https://www.home-assistant.io/integrations/plex/#service-play_media

YAML example below, but if using the UI editor: `target` would be `entity_id`, `content` would be `content_id`, and `content type` would be `media_content_id`

YAML example:

```yaml
entity_id: media_player.plex_player
media_content_type: PLAYLIST
media_content_id: '{ "playlist_name": "all music", "shuffle": "1" }'
```

It seems as if you've configured the default log level of HA to `debug` instead of only Plex Assistant. More info on that here: https://www.home-assistant.io/integrations/logger/

**Comment by miketunes** [comment]
Ok trying to fix the logging, so instead of adding this to configuration.yaml:
logger: 
  logs:
    custom_components.plex_assistant: debug

I should change it to this instead?  
logger: fatal
  logs: fatal
    custom_components.plex_assistant: debug

**Comment by maykar** [comment]
I'd do:

```
logger:
  default: warning
  logs:
    custom_components.plex_assistant: debug
```

**Comment by miketunes** [comment]
Tried using YAML, with your example but the call service is greyed out:
https://imgur.com/a/RyuGQbn

**Comment by maykar** [comment]
Try this, also do you have a media_player entity called `media_player.chromecast` and a playlist called `everything`? That was just an example.

```
service: media_player.play_media
target:
  entity_id: media_player.chromecast
data:
  media_content_type: PLAYLIST
  media_content_id: 'plex://{ "playlist_name": "everything", "shuffle": "1" }'
```
