### ISSUE TITLE
Sensor picks up on some devices as having no name

### ISSUE THREAD

**Issue by KevinX8** [maykar/plex_assistant#27]
For both my PS4 Pro and Philips Smart TV the included sensor sees them as having no name and are just shown as device1, ,device2 with the middle being what I assume the TV is supposed to be. Using the device id's provided by the plex server intergration also does not work so I have no way of addressing my devices. I am able to address my pc successfully, however multiple instances of chrome all show up as chrome on the sensor.
Config as below:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
- platform: plex_assistant
plex_assistant:
  url: 'http://192.168.1.69:32400'
  token: '*****'
  default_cast: 'Downstairs TV'
  language: 'en'
  tts_errors: true
  aliases:
    Downstairs TV: plex_plex_for_playstation_4_playstation_4_pro
    Upstairs PC: Chrome
    PS4: plex_plex_for_playstation_4_playstation_4_pro
    PS 4: plex_plex_for_playstation_4_playstation_4_pro
automation:
  - alias: Plex Assistant Automation
    trigger:
    - event_data:
        action: call_service
      event_type: ifttt_webhook_received
      platform: event
    condition:
      condition: template
      value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
    action:
    - data_template:
        command: "{{ trigger.event.data.command }}"
      service_template: '{{ trigger.event.data.service }}'

```
