### ISSUE TITLE
Error in configuration.yaml when setting up Plex assistant with Home Assistant's conversation

### ISSUE THREAD

**Issue by Maximillion195** [maykar/plex_assistant#49]
First off this looks awesome, great job! Haven't tried anything like this since Phlex which didn't go so well so really excited to use this.

When setting up Plex Assistant with Home Assistant's conversation integration in the configuration.yaml, I get this error when starting Home Assistant. I copied the exact code you have on the readme without changing anything. Thanks for any help.

**Home Assistant Error:**

```
2020-09-24 23:28:05 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while parsing a block collection
  in "/config/configuration.yaml", line 115, column 6
expected <block end>, but found '<scalar>'
  in "/config/configuration.yaml", line 116, column 18
2020-09-24 23:28:05 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: while parsing a block collection
  in "/config/configuration.yaml", line 115, column 6
expected <block end>, but found '<scalar>'
  in "/config/configuration.yaml", line 116, column 18. Activating safe mode
```

**configuration.yaml** (ommited my url and token)

```
plex_assistant:
  url: 'MYURL'
  token: 'MYTOKEN'
  default_cast: 'Lounge TV'
  language: 'en'
  tts_errors: true

conversation:
  intents:
    PlexAssistant:
     # These trigger commands can be changed to suit your needs.
     - Tell Plex to {command}
     - {command} with Plex

intent_script:
  PlexAssistant:
    speech:
      text: Command sent to Plex.
    action:
      service: plex_assistant.command
      data_template:
        command: "{{command}}"
```

**Comment by maykar** [comment]
What is on line 115 and line 116 of your configuration.yaml file?

**Comment by Maximillion195** [comment]
It's these lines

```
#      - Tell Plex to {command}
#      - {command} with Plex
```

I actually just got it set up with IFTTT and its working perfectly! Happy to close this or carry on if you think it's actually a bug and not me messing something up :)

**Comment by maykar** [comment]
That error usually means there was a missed open quotation or something similar. Fairly certain there is something in your configuration that is wonky. Possibly something before the `plex_assistant:` line. The config that you've shown is valid yaml (unless I'm missing something) and working on my main HA system and dev setup.

**Comment by Maximillion195** [comment]
I managed to get it working, it needed double quotes around the strings

```
conversation:
  intents:
    PlexAssistant:
     - "Tell Plex to {command}"
     - "{command} with Plex"

intent_script:
  PlexAssistant:
    speech:
      text: Command sent to Plex.
    action:
      service: plex_assistant.command
      data_template:
        command: "{{command}}"
```
