### ISSUE TITLE
Intent needs to be Plex instead of PlexAssistant for Google Assistant

### ISSUE THREAD

**Issue by mrmessy** [maykar/plex_assistant#56]
The intent in the readme needs to be just Plex instead of PlexAssistant to work with Google Assistant.
ie change PlexAssistant to Plex in https://github.com/maykar/plex_assistant#home-assistant-conversation-setup
so that it is the same as that in https://github.com/maykar/plex_assistant#in-home-assistant-3
```yaml
intent_script:
  Plex:
    speech:
      text: Command sent to Plex.
    action:
      - service_template: plex_assistant.command
        data_template:
          command: "{{command}}"
```
