### ISSUE TITLE
Sensor not detecting clients and commands not being sent to Plex

### ISSUE THREAD

**Issue by ashmores** [maykar/plex_assistant#67]
Hi

I'm running Home Assistant 0.117.5 on ESX via the OVA with HACS 1.6.2 and Plex Assistant 0.3.0
I've followed the guide and below is my configuration.yaml

```
plex_assistant:
  url: 'http://192.168.1.225:32400'
  token: 'xxxxxxxxxxxxxxxxxx'
  default_cast: 'Bedroom TV'
  language: 'en'
  tts_errors: true
  aliases:
    Downstairs TV: 'LG 55UJ701V-ZC'
    Bedroom TV: 'LG 49UK6470PLC'
```

```
  sensor:
- platform: plex_assistant
```
```
automation:
  - alias: Plex Assistant Automation
    trigger:
    - event_data:
        action: call_service
      event_type: ifttt_webhook_received
      platform: event
    condition:
      condition: template
      value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
    action:
    - data_template:
        command: "{{ trigger.event.data.command }}"
      service_template: '{{ trigger.event.data.service }}'
```

```
intent_script:
  Plex:
    speech:
      text: Command sent to Plex.
    action:
      - service_template: plex_assistant.command
        data_template:
          command: "{{command}}"
```

I've setup ifttt and in the states under developer on home assistant I can see the date and time update on the automation.plex_assistant_automation to show the command has been received but nothing happens.  I've also entered the command manually as below through the service option and get the following error

 Service
plex_assistant.command
Service Data (YAML, optional)
command: Play Evil Dead on the Bedroom TV

Failed to call service plex_assistant/command. type object 'PA' has no attribute 'client_ids'

I'm hoping you can spot something I've done wrong but I've been over this several times I can't see what it could be.
