### ISSUE TITLE
Automation code format differs is using Config.yaml vs Auto.yaml

### ISSUE THREAD

**Issue by XoniBlue** [maykar/plex_assistant#81]
Having told the config file we are going to use a separate file for automations, we can no longer use the initial formatted code supplied for installation. As well any automations you have created through the UI or have in your automations.yaml file will no longer work as they are being overridden by the automations section you have added to the configuration.yaml file if you followed the directions. 

To add this automation via the ui or to your automations.yaml file it must be formatted like so 

```yaml

alias: Plex Assistant Automation
trigger:
    - event_data:
       action: call_service
      event_type: ifttt_webhook_received
      platform: event
condition:
        condition: template
        value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
action:
      - data_template:
          command: "{{ trigger.event.data.command }}"
        service_template: '{{ trigger.event.data.service }}'
        ###################################################
        # The following 4 lines are the added debug lines #
        ###################################################
      - service: system_log.write
        data:
          message: "{{ trigger.event.data.command }}"
          level: warning 

```
